# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gci
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - staticcheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gosec:
    # Exclude generated files
    exclude-generated: true
    excludes:
      - G601 # not applicable in go 1.22 anymore
